In [1]:
my_list = [i for i in range(0,100,20)]

In [2]:
import numpy as np

In [3]:
np.array(my_list)

array([ 0, 20, 40, 60, 80])

In [4]:
my_matrix = [[1,2,3],[7,8,9],[4,5,6]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])

In [7]:
np.arange(0,50,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [9]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones((6,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.linspace(0,5,9)

array([0.   , 0.625, 1.25 , 1.875, 2.5  , 3.125, 3.75 , 4.375, 5.   ])

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
np.eye(5) * [i for i in range(5)]

array([[0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 2., 0., 0.],
       [0., 0., 0., 3., 0.],
       [0., 0., 0., 0., 4.]])

In [17]:
np.random.rand(5)

array([0.69316456, 0.7502097 , 0.1565379 , 0.59518808, 0.4368562 ])

In [18]:
np.random.rand(5,5)

array([[0.8627958 , 0.8891717 , 0.33455571, 0.69718375, 0.82076281],
       [0.73500194, 0.71182804, 0.63760638, 0.70291752, 0.71480459],
       [0.49682569, 0.27299657, 0.16214532, 0.41014828, 0.20298238],
       [0.66200021, 0.23196445, 0.91591735, 0.76779757, 0.20523689],
       [0.66294803, 0.2155859 , 0.90540598, 0.65159376, 0.48216287]])

In [19]:
np.random.randn(6)

array([-0.60277437, -1.37485217, -0.51783832,  0.86684123,  0.64450097,
       -1.15465952])

In [21]:
np.random.randint(10,94,(5,6))

array([[45, 72, 42, 90, 16, 18],
       [25, 81, 74, 86, 58, 80],
       [65, 64, 22, 63, 23, 68],
       [81, 66, 62, 79, 81, 67],
       [88, 63, 81, 24, 85, 81]])

In [24]:
arr = np.linspace(0,75,25)

In [25]:
arr.reshape(5,5)

array([[ 0.   ,  3.125,  6.25 ,  9.375, 12.5  ],
       [15.625, 18.75 , 21.875, 25.   , 28.125],
       [31.25 , 34.375, 37.5  , 40.625, 43.75 ],
       [46.875, 50.   , 53.125, 56.25 , 59.375],
       [62.5  , 65.625, 68.75 , 71.875, 75.   ]])

In [26]:
rarr = np.random.randint(0,200,26)

In [27]:
rarr.max()

192

In [28]:
rarr.min()

25

In [30]:
rarr.argmax()

4

In [31]:
rarr.argmin()

20

In [32]:
rarr

array([ 98,  86, 141,  94, 192,  35,  32, 177, 126, 147,  30,  55, 118,
        46, 176, 183,  69, 188,  96, 160,  25, 104, 157, 130, 123,  62])

In [33]:
arr.dtype

dtype('float64')